spring:
  application:
    name: costcook
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/costcook_db
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: never
  upload:
    location: C:\\Users\\WD\\Desktop\\costcook-image
  mail:
    host: smtp.gmail.com # Google SMTP 서버 주소
    port: 587 # SMTP 포트
    username: pbc9236@gmail.com # 발송자 이메일
    password: scjtbmripfszsirb # 발송자 이메일 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
          enable: true
jwt:
  issuer: costcook
  secret_key: mysecretmysecretmysecretmysecret
  access_duration: 1800000 # 30분을 ms로 변환
  refresh_duration: 604800000 # 1주을 ms로 변환
